fix/FORNUL-284, FORNUL-285, FORNUL-286 (#12)
* fix: Deleting deprecated actions we used and creating new scripts
Ticket: FORNUL-284

* feat: repository tagging for fornul_pipelines added
Ticket: 286

* fix: renaming workflows
Ticket: FORNUL-285

diff --git a/.github/workflows/labeling.yml b/.github/workflows/labeling.yml
--- a/.github/workflows/labeling.yml
+++ b/.github/workflows/labeling.yml
@@ -1,4 +1,4 @@
-name: PR label check and comment 
+name: PR label check 
 
 on:
   workflow_call:
@@ -7,22 +7,25 @@ on:
         required: true
 
 jobs:
-  Label-check:
+  label-check:
     runs-on: ubuntu-latest
+
     steps:
-
-      - name: checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      - name: Check labels
-        uses: docker://agilepathway/pull-request-label-checker:latest
-        with:
-          one_of: version:major,version:minor,version:patch,no_release
-          mode: exactly
-          count: 1
-          repo_token: ${{ secrets.repo_token }}
 
-  Reminding_comment:
-    needs: Label-check
+      - name: Check labels
+        run: |
+          labels=$(jq --raw-output '.pull_request.labels[] | .name' "$GITHUB_EVENT_PATH")
+          if [[ $labels =~ ^(no_release|version:minor|version:major|version:patch)$ ]]; then
+            echo "Exactly one label is selected."
+          else
+            echo "Error: You need to select exactly one label."
+            exit 1
+          fi
+
+  comment:
+    needs: label-check
     if: failure()
     runs-on: ubuntu-latest
     steps:
